#!/bin/bash
SERVICE_VERSION=$(cat version)
export APP_PORT=7001
export PROJECT_NAME="kotlin-app-template"
export PROJECT_VERSION="$SERVICE_VERSION"
java -jar "kotlin-app-template-$SERVICE_VERSION.jar"